###Retrieve details of a single SWIFT code whether for a headquarters or branches
GET http://localhost:8080/v1/swift-codes/AIPOPLP1XXX
Content-Type:  application/json


### GET with the countryISO2Code
GET http://localhost:8080/v1/swift-codes/country/AL
Content-Type: application/json

###
POST http://localhost:8080/v1/swift-codes/
Content-Type: application/json

{
  "address": "123 Main Street, New York, NY",
  "bankName": "Bank of America",
  "countryISO2": "US",
  "countryName": "United States",
  "isHeadquarter": true,
  "swiftCode": "BOFAUS3N"
}

###
DELETE  http://localhost:8080/v1/swift-codes/BOFAUS3N
Content-Type: application/json
