global:
  scrape_interval: 15s # Scrap the metrics every 15 second

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:8080']
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']