definitions:
  model.ErrorResponse:
    properties:
      error:
        type: string
      message:
        type: string
      status_code:
        type: integer
    type: object
  model.SwiftCode:
    properties:
      address:
        type: string
      bankName:
        type: string
      codeType:
        type: string
      countryISO2:
        type: string
      countryName:
        type: string
      id:
        type: integer
      isHeadquarter:
        type: boolean
      swiftCode:
        type: string
      timezone:
        type: string
      townName:
        type: string
    type: object
  model.SwiftCodeAddRequest:
    properties:
      address:
        maxLength: 255
        minLength: 5
        type: string
      bankName:
        maxLength: 255
        minLength: 3
        type: string
      countryISO2:
        type: string
      countryName:
        maxLength: 100
        minLength: 2
        type: string
      isHeadquarter:
        type: boolean
      swiftCode:
        type: string
    required:
    - address
    - bankName
    - countryISO2
    - countryName
    - isHeadquarter
    - swiftCode
    type: object
info:
  contact: {}
paths:
  /swift-code:
    delete:
      consumes:
      - application/json
      description: Delete a SwiftCode by its value.
      parameters:
      - description: Swift Code
        in: query
        name: swift-code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SwiftCode'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Delete SwiftCode
      tags:
      - SwiftCode
    get:
      consumes:
      - application/json
      description: Retrieve a SwiftCode by its code.
      parameters:
      - description: SwiftCode
        in: query
        name: swift-code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.SwiftCode'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get SwiftCode
      tags:
      - SwiftCode
    post:
      consumes:
      - application/json
      description: Create a new SwiftCode entry.
      parameters:
      - description: SwiftCode Add Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.SwiftCodeAddRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.SwiftCode'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Create SwiftCode
      tags:
      - SwiftCode
  /swift-code/{countryISO2code}:
    get:
      description: Retrieve banks using the ISO2 country code.
      parameters:
      - description: Country ISO2 Code
        in: path
        name: countryISO2code
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.SwiftCode'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/model.ErrorResponse'
      summary: Get Banks by ISO2
      tags:
      - SwiftCode
swagger: "2.0"
